spring.application.name=gestao_vagas
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

server.address=0.0.0.0

security.token.secret=JAVAGAS_@123#
security.token.secret.candidate=JAVAGAS_@123#CANDIDATE

token.sonar = token=sqp_ce158cfab1fa5fb0f11235680610ae595220d463

#management.endpoints.web.exposure.include=health,metrics,prometheus
#management.endpoints.health.enabled=true
#management.endpoints.health.show-details=always

management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
management.metrics.tags.application=gestao_vagas
management.metrics.enable.jvm=true
management.metrics.enable.process=true
management.metrics.enable.system=true
management.metrics.enable.http=true
management.metrics.enable.tomcat=true

db-gestao-vagas = dbname
gestaovagas = username